### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by awikkerink** [BrightspaceUI/text-input#2]
https://github.com/BrightspaceUI/text-input/blob/master/d2l-text-input.html#L65
```css
input:invalid,
input[aria-invlid='true'] {
	border-color: var(--d2l-color-cinnabar);
}
```
